apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jepsen
      image: hub.pingcap.net/cwen/ubuntu_jepsen:latest
      resources:
        limits:
          cpu: 8
          memory: 16Gi
        requests:
          cpu: 4
          memory: 8Gi
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
    - name: dind
      image: hub.pingcap.net/cwen/docker:dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
  volumes:
    - name: dind-storage
      emptyDir: {}
